# Generated by Django 4.2.2 on 2023-06-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=120, unique=True)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('password', models.CharField(max_length=120)),
                ('superuser', models.BooleanField(default=False)),
            ],
        ),
    ]
