# Generated by Django 4.2.2 on 2023-06-18 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newton_larson', '0003_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='problem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('problem', models.CharField(max_length=220)),
                ('x', models.FloatField(max_length=90)),
                ('error', models.FloatField(max_length=5)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newton_larson.user')),
            ],
        ),
    ]
